### ISSUE TITLE
Evaluation!

### ISSUE THREAD

**Issue by akkasi** [allenai/mup#1]
Could you please provide some information on preparing the reference summary file for the **validation** data? i.e. since there are several summareis per each paper, should all the summaries be concatentaed as the reference for a given paper?

**Comment by armancohan** [comment]
You mean for submission? The submission file should be in csv format (where each row has `paper_id`, `summary` columns). More information is in the [readme](https://github.com/allenai/mup#submission-instructions). Let me know if you have further questions.

**Comment by akkasi** [comment]
No! not for submission.  Right now, except the test data, there are two datasets available: training data for model training and validation data for the validation purpose. So, the reference summaries for the validation data must be available. My question is that, how we should extract the reference summaries for the papers in **validation dataset**.

**Comment by armancohan** [comment]
Both training and validation data come with reference summaries (under the `summary` field). An entry will be repeated if there are multiple reference summaries. 
For example if a particular paper has 3 reference summaries, in the `csv` file there is 3 rows for that paper, each with identifcal text but different summary. Same for `jsonl` file. It depends on the system developer on how they want to treat multiple summaries per paper.  Does this answer your question?

**Comment by akkasi** [comment]
Thanks. Now, it is clear.

**Comment by armancohan** [comment]
Closing the issue as this seems resolved.
